In [1]:
import pandas as pd

In [2]:
patients = pd.read_csv('ClinicalPreprocessing/ProcessedData/patients.csv')
patients.head()

,case_id,submitter_id,primary_site,disease_type,consent_type,index_date,state,updated_datetime,days_to_consent,lost_to_followup,ethnicity,gender,race,vital_status,age_at_index,days_to_birth,days_to_death,population_group,country_of_residence_at_enrollment
0,005a6517-2e5a-4ea3-ab36-531522723607,TCGA-61-1740,Ovary,"Cystic, Mucinous and Serous Neoplasms",Consent by Death,Diagnosis,released,2025-01-06T21:35:19.822934-06:00,NaN,NaN,not hispanic or latino,female,white,Dead,71.0,-26169.0,74.0,NaN,NaN
1,00630714-7ab3-44e1-afff-186300edae44,TCGA-13-0761,Ovary,"Cystic, Mucinous and Serous Neoplasms",NaN,Diagnosis,released,2025-01-06T20:22:17.160596-06:00,NaN,NaN,not hispanic or latino,female,white,Dead,51.0,-18697.0,1156.0,NaN,NaN
2,01abf2cf-541c-4610-8ce8-318016db6e59,TCGA-25-2390,Ovary,"Cystic, Mucinous and Serous Neoplasms",Consent by Death,Diagnosis,released,2025-01-06T21:14:34.783233-06:00,NaN,NaN,not reported,female,not reported,Not Reported,80.0,-29257.0,NaN,NaN,NaN
3,01ea6354-137b-47f3-9021-a01a382b1147,TCGA-29-1766,Retroperitoneum and peritoneum,"Cystic, Mucinous and Serous Neoplasms",Informed Consent,Diagnosis,released,2025-01-06T21:17:03.900338-06:00,1015.0,NaN,not reported,female,white,Dead,74.0,-27359.0,1199.0,NaN,NaN
4,02594e5e-8751-47c1-9245-90c66984b665,TCGA-09-2051,Ovary,"Cystic, Mucinous and Serous Neoplasms",Informed Consent,Diagnosis,released,2025-01-06T21:23:02.309774-06:00,1787.0,NaN,not hispanic or latino,female,white,Alive,42.0,-15650.0,NaN,Ashkenazi Jew,NaN

In [3]:
follow_ups = pd.read_csv('ClinicalPreprocessing/ProcessedData/follow_ups.csv')
follow_ups.head()

,follow_up_id,case_id,submitter_id,timepoint_category,days_to_follow_up,disease_response,progression_or_recurrence,progression_or_recurrence_type,evidence_of_recurrence_type,days_to_recurrence,ecog_performance_status,karnofsky_performance_status
0,1d266ca2-f3e7-473d-93b0-2b8f2af773b8,005a6517-2e5a-4ea3-ab36-531522723607,TCGA-61-1740_follow_up,Last Contact,74.0,WT-With Tumor,NaN,NaN,NaN,NaN,NaN,NaN
1,781533f7-4c3d-423f-aa83-9718cd9a9f12,005a6517-2e5a-4ea3-ab36-531522723607,TCGA-61-1740_follow_up3,Prior to Adjuvant Therapy,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN
2,a9f13da7-d7da-4cd4-b3a0-658b70ba3404,005a6517-2e5a-4ea3-ab36-531522723607,TCGA-61-1740_follow_up2,Follow-up,74.0,WT-With Tumor,NaN,NaN,NaN,NaN,NaN,NaN
3,11df2a10-76aa-4a25-9d85-88a32930b661,00630714-7ab3-44e1-afff-186300edae44,TCGA-13-0761_follow_up5,Post Initial Treatment,424.0,NaN,Yes,Unknown,NaN,NaN,NaN,NaN
4,36407ad0-6db2-4a93-aa80-43fce25d9195,00630714-7ab3-44e1-afff-186300edae44,TCGA-13-0761_follow_up4,Post Initial Treatment,424.0,NaN,Yes,Unknown,Convincing Image Source,424.0,NaN,NaN

In [4]:
diagnoses = pd.read_csv('ClinicalPreprocessing/ProcessedData/diagnoses.csv')
diagnoses.head()

,diagnosis_id,case_id,submitter_id,days_to_diagnosis,primary_diagnosis,morphology,icd_10_code,classification_of_tumor,diagnosis_is_primary_disease,tissue_or_organ_of_origin,...,figo_stage,tumor_grade,year_of_diagnosis,age_at_diagnosis,prior_malignancy,synchronous_malignancy,prior_treatment,method_of_diagnosis,residual_disease,days_to_last_follow_up
0,6bce9673-5223-59f5-b869-2366b5e46652,005a6517-2e5a-4ea3-ab36-531522723607,TCGA-61-1740_diagnosis,0.0,"Serous cystadenocarcinoma, NOS",8441/3,C56.9,primary,True,Ovary,...,Stage IIIC,G3,2005.0,26169.0,not reported,Not Reported,No,Surgical Resection,NaN,74.0
1,6e210a80-985b-457d-903f-65cdb7101cce,00630714-7ab3-44e1-afff-186300edae44,TCGA-13-0761_diagnosis3,424.0,Unknown,Unknown,NaN,Unknown,False,Not Reported,...,NaN,NaN,NaN,19121.0,NaN,NaN,Yes,NaN,NaN,NaN
2,f12065b8-bf43-4d3d-a6b2-f3e42796d92f,00630714-7ab3-44e1-afff-186300edae44,TCGA-13-0761_diagnosis2,424.0,"Serous cystadenocarcinoma, NOS",8441/3,NaN,recurrence,False,Not Reported,...,NaN,NaN,NaN,19121.0,NaN,NaN,Yes,NaN,NaN,NaN
3,fa91f476-c060-5d7c-8454-e8724950c497,00630714-7ab3-44e1-afff-186300edae44,TCGA-13-0761_diagnosis,0.0,"Serous cystadenocarcinoma, NOS",8441/3,C56.9,primary,True,Ovary,...,Stage IV,G3,2006.0,18697.0,not reported,Not Reported,No,Surgical Resection,NaN,1156.0
4,dc0adbeb-b689-5242-9257-1d892eef26b1,01abf2cf-541c-4610-8ce8-318016db6e59,TCGA-25-2390_diagnosis,0.0,"Serous cystadenocarcinoma, NOS",8441/3,C56.9,primary,True,Ovary,...,NaN,NaN,2003.0,29257.0,not reported,Not Reported,No,NaN,NaN,NaN

In [5]:
pathology = pd.read_csv('ClinicalPreprocessing/ProcessedData/pathology_details.csv')
pathology.head()

,pathology_detail_id,diagnosis_id,case_id,submitter_id,consistent_pathology_review,vascular_invasion_present,lymphatic_invasion_present,residual_tumor_measurement
0,ae9a7cf9-20ab-40c7-ade0-57ee2336e169,6bce9673-5223-59f5-b869-2366b5e46652,005a6517-2e5a-4ea3-ab36-531522723607,TCGA-61-1740_pathology_detail,Not Reported,Yes,Yes,>20 mm
1,9bcca55a-33cd-466a-9b77-43c63fdfa378,fa91f476-c060-5d7c-8454-e8724950c497,00630714-7ab3-44e1-afff-186300edae44,TCGA-13-0761_pathology_detail,Not Reported,NaN,NaN,No macroscopic disease
2,b0c6a0a1-92c5-4ef8-83d7-04b142ef0444,dc0adbeb-b689-5242-9257-1d892eef26b1,01abf2cf-541c-4610-8ce8-318016db6e59,TCGA-25-2390_pathology_detail,Not Reported,NaN,NaN,NaN
3,2fd85542-2590-4e74-bf19-fdcc9554ff43,c3f472b3-884c-5a6a-b8ef-99c8a29a6b21,01ea6354-137b-47f3-9021-a01a382b1147,TCGA-29-1766_pathology_detail,Not Reported,NaN,NaN,11-20 mm
4,9da49dbf-bcf2-4abf-b47d-5ff663d1d7b0,1d60ab6b-010d-5421-9e30-11b38b71be6e,02594e5e-8751-47c1-9245-90c66984b665,TCGA-09-2051_pathology_detail,Not Reported,Yes,Yes,No macroscopic disease

In [6]:
treatments = pd.read_csv('ClinicalPreprocessing/ProcessedData/treatments.csv')
treatments.head()

,treatment_id,diagnosis_id,case_id,submitter_id,treatment_type,treatment_or_therapy,treatment_intent_type,initial_disease_status,days_to_treatment_start,days_to_treatment_end,...,treatment_dose,treatment_dose_units,route_of_administration,number_of_cycles,number_of_fractions,treatment_anatomic_sites,treatment_outcome,clinical_trial_indicator,prescribed_dose,prescribed_dose_units
0,cb2dc0c4-bd49-58f3-aa30-fc5f15c8fd08,6bce9673-5223-59f5-b869-2366b5e46652,005a6517-2e5a-4ea3-ab36-531522723607,TCGA-61-1740_treatment,Hormone Therapy,yes,Adjuvant,NaN,23.0,74.0,...,1020.0,mg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,e458f367-1154-49ad-9075-b5ab3b8393f7,6bce9673-5223-59f5-b869-2366b5e46652,005a6517-2e5a-4ea3-ab36-531522723607,TCGA-61-1740_treatment2,"Radiation Therapy, NOS",no,Adjuvant,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,bc3f7a1c-f368-4b1d-9a38-d7d137243d40,f12065b8-bf43-4d3d-a6b2-f3e42796d92f,00630714-7ab3-44e1-afff-186300edae44,TCGA-13-0761_treatment4,"Pharmaceutical Therapy, NOS",yes,NaN,Recurrent Disease,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,cf790fb7-935d-4d36-8b0f-e82fba6b0241,f12065b8-bf43-4d3d-a6b2-f3e42796d92f,00630714-7ab3-44e1-afff-186300edae44,TCGA-13-0761_treatment5,"Radiation Therapy, NOS",no,NaN,Recurrent Disease,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7d185e00-771d-4f4a-93a3-3628a29aaef3,fa91f476-c060-5d7c-8454-e8724950c497,00630714-7ab3-44e1-afff-186300edae44,TCGA-13-0761_treatment3,"Radiation Therapy, NOS",no,Adjuvant,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
image_mapping = pd.read_csv('ClinicalPreprocessing/ProcessedData/image_clinical_annotation_map.csv')
image_mapping.head()

,image_filename,full_path,patient_id,case_id,series_instance_uid,study_instance_uid,primary_diagnosis,figo_stage,tumor_grade,icd_10_code,laterality,diagnosis_id,days_to_diagnosis,annotation_count,annotation_notes,annotation_categories
0,patient_TCGA-09-0364_series_1.3.6.1.4.1.14519....,../ImageCollection/dicom_images/patient_TCGA-0...,TCGA-09-0364,6746533a-8d0b-4ebc-87ec-49c8738121a8,1.3.6.1.4.1.14519.5.2.1.7695.4007.115512319570...,1.3.6.1.4.1.14519.5.2.1.7695.4007.250730721548...,"Serous cystadenocarcinoma, NOS",Stage IIC,G3,C56.9,Right,42b4a2fe-7c3d-5839-b189-e22b4b061c28,0,6,Real somatic mutations were mistakenly labeled...,General; Barcode incorrect
1,patient_TCGA-09-2044_sop_1.3.6.1.4.1.14519.5.2...,../ImageCollection/dicom_images/patient_TCGA-0...,TCGA-09-2044,7d03ddb6-f3fe-4b50-8bba-514aa65e7d0e,1.3.6.1.4.1.14519.5.2.1.7695.4007.308257434883...,1.3.6.1.4.1.14519.5.2.1.7695.4007.192275693252...,"Serous cystadenocarcinoma, NOS",Stage IIB,G3,C56.9,Right,44bb6d41-522c-5051-b9a5-d0fb8e4f3d93,0,20,WXS data may no longer be available for this a...,General
2,patient_TCGA-09-2044_sop_1.3.6.1.4.1.14519.5.2...,../ImageCollection/dicom_images/patient_TCGA-0...,TCGA-09-2044,7d03ddb6-f3fe-4b50-8bba-514aa65e7d0e,1.3.6.1.4.1.14519.5.2.1.7695.4007.308257434883...,1.3.6.1.4.1.14519.5.2.1.7695.4007.192275693252...,"Serous cystadenocarcinoma, NOS",Stage IIB,G3,C56.9,Right,44bb6d41-522c-5051-b9a5-d0fb8e4f3d93,0,20,WXS data may no longer be available for this a...,General
3,patient_TCGA-09-2045_sop_1.3.6.1.4.1.14519.5.2...,../ImageCollection/dicom_images/patient_TCGA-0...,TCGA-09-2045,3768d34f-1527-40db-b116-cd80cee5ec3a,1.3.6.1.4.1.14519.5.2.1.7695.4007.125519796440...,1.3.6.1.4.1.14519.5.2.1.7695.4007.136836036689...,"Serous cystadenocarcinoma, NOS",Stage IV,G2,C56.9,Bilateral,0ffcd742-a709-52d5-b7ac-ea8a72376fdf,0,6,Variants from SomaticSniper are not included.;...,General
4,patient_TCGA-09-2051_sop_1.3.6.1.4.1.14519.5.2...,../ImageCollection/dicom_images/patient_TCGA-0...,TCGA-09-2051,02594e5e-8751-47c1-9245-90c66984b665,1.3.6.1.4.1.14519.5.2.1.7695.4007.315918915592...,1.3.6.1.4.1.14519.5.2.1.7695.4007.276045886850...,"Serous cystadenocarcinoma, NOS",Stage IIIC,G3,C56.9,Bilateral,1d60ab6b-010d-5421-9e30-11b38b71be6e,0,6,Pairwise comparisons of expression results bet...,General